cluster_name: opossum
domain: lab.shortrib.net
cluster_image_name: metal-amd64.iso
default_password: ENC[AES256_GCM,data:r7AXffyMcAsLc0Uqr07rB0vsyCjNqodcjQ==,iv:LFAeBJeVKlicyQZyOvO1nlWYSD70T/DwlFrpZlpJAuM=,tag:sEsM+MBlUHJj3Q48JYH57A==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:01:0a
    control_plane_cidr: 10.24.1.0
    load_balancer_cidr: 10.23.1.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: 10.18.1.240
    username: admin
    password: ENC[AES256_GCM,data:rkagB2Pg9FC/17hlp9yFa9EULrbl94ApdasWw/Tv,iv:jSDSjykRRJPxerrXsvp9vZKZecjWBKsh+JuGS3IvqvY=,tag:Zh5muCKS9J9eHIku0RUutw==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
acme:
    email: crdant@shortrib.io
cloudflare:
    api_token: GXvj-gJLYFNzBV97rBitL3_JERgSziM5Z4CbLeKm
tailscale:
    client_id: kj6YyWz1Hp11CNTRL
    client_secret: ENC[AES256_GCM,data:ThyXA5LIeNH5MxshJp/8Niu7LOMF6G8FXMcPJDhMmcIxVX82uLAla6s9k2dn+XTPOrUR0DbCjEsTIgbDeHixkQ==,iv:fxYC2y/cpE+VMh5XB78Iom6SvXsWVWjFi8S7g+Nqzlo=,tag:6TjtOIikzaZVWMOTyGXkWw==,type:str]
sops:
    lastmodified: "2026-01-12T03:20:00Z"
    mac: ENC[AES256_GCM,data:UIyYxPW95M4fku7voEI6bgVkXjVzW9J6HVt0lQOYIF866VwT9Qm7sbsyWgL0pIRhnF9jfmfA/4p6CJ4nK02jU7ZZYulR1ABDjl1/A0MoEiJJjmglgtXcO6zuzfId2gta8uOQujY++rQukAqiwTPJvO7NrjKWNyQinR2w9dhAy2o=,iv:Mg2dXYpDMIqKD62XrVLoZqvVeIKZqDY5s2vUAS8TWl0=,tag:kA3nzsWjPsqon9e17TPByQ==,type:str]
    pgp:
        - created_at: "2026-01-12T03:20:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAbbEGJ6DME7NaLfX8pbv6zdQxadC/UEluEzF2C0BgF1ow
            nmx9AFMN8hxUgFgnZdZSqTvxHp0xQ9/bnVdLu6/6ynlCtqFmzi53fDbGF8jeWGh9
            0lwBPH11s1pdXwOSx1ZivPJ52pFedE7g3IfXfC373GobVKSPytQwUBzNUkG+q3I9
            WLLTT7JubGazpj1c8KyaBfKS6TNvKg8KOv0ro/I+3O2zXcqm0myIIkfMbzgAGg==
            =D+LT
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
