cluster_name: opossum
domain: lab.shortrib.net
cluster_image_name: metal-amd64.iso
default_password: ENC[AES256_GCM,data:lM1ub0n1q+gQSBJG9ojOlbtKJf6feNX6Pw==,iv:/vzNk7FmRiWDhfTYh0jCbhc/GdaiisUvLR5mI0jJ0zM=,tag:ppsugmmuxhxmvhLDwNQE/A==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:01:0a
    control_plane_cidr: 10.24.1.0
    control_plane_cidr_v6: 2600:4040:5c41:94b4:5054:ff:fe18:10a
    load_balancer_cidr: 10.23.1.0/24
    load_balancer_cidr_v6: 2600:4040:5c41:94b4::1:0/112
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: 10.18.1.240
    username: admin
    password: ENC[AES256_GCM,data:DAESB/5CpdICF9SajKLMjptktpahNSq0FytCN5bc,iv:kXu5FY4i3Wd7LOEgwU8ss6yMVsg4WTkLBkht6l4ZXYw=,tag:Pg3EP5//STYZalAivBQPzQ==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
acme:
    email: crdant@shortrib.io
cloudflare:
    api_token: GXvj-gJLYFNzBV97rBitL3_JERgSziM5Z4CbLeKm
tailscale:
    client_id: kj6YyWz1Hp11CNTRL
    client_secret: ENC[AES256_GCM,data:07gnI8uzAVuu8UHA7cLqvzgrhsko/aXvLQv13GiFi4HEtpYY9dAQCG7cdm3CdUvh4dOQHzh3uzZLDz3GMfL7Rw==,iv:gyfRQlTwLSGkIfILoYGog8CCH3xK4naEreTqM+ku9YU=,tag:c3cxDkGCsQqj9MOdu1kkqA==,type:str]
sops:
    lastmodified: "2026-01-11T21:31:40Z"
    mac: ENC[AES256_GCM,data:bukrslKGNDgVolHJ+Sn7tjXyRo+E0q9BhlzKJyBXEhOexbRJlT3ldC4BGzzNWW1uZbzdNfW1X6KxsTTfKd4SlCdusJIyPudLZ8n3DtvglhI0icSJ1YMlK0qd/oWWsOKJiCrumbo3e4nKPeGAHaAiBcqT9aJJbY5sp2AOEps/4w4=,iv:TJRacUuzdHm4VfNWltPdRv8RFEbS6UMoxqFKtVky3LQ=,tag:a3YVRerxwSPfAFC55HGTrw==,type:str]
    pgp:
        - created_at: "2026-01-11T21:31:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAd9Acm2xguz/ohuYLWlrenlbsKXUk6h2Ms43CvUVWbi0w
            IGkpv1dMIqY+K9JdxC9x2iRKjX+n/RcVXLc7z+lF5duSs6sKQ231OuR4zjlo0mS8
            0lwBSz+4XKFeDnhEFPkxXJKtSe4G82BXzGh3BYcVu5LNMEU99bJ77iy7TVemkgWx
            VhqwByGdXKLj44bacDV0Z+EqCP/qKU9hIzZdPi80oQLAZxwwEQNJP/jNYpvMNA==
            =pQVc
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
