cluster_name: opossum
domain: lab.shortrib.net
cluster_image_name: metal-amd64.iso
default_password: ENC[AES256_GCM,data:hvh2MhiviiMXvSmDUDDTXzYL2u0fyS9Ahw==,iv:sWdetxQsry+t8ywZOyifrGngyFlPtw+nmYwS+DZMHuY=,tag:9GZFQAChimOKhhd1BdIxIQ==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:01:0a
    kubernetes_cidr: 10.24.0.0/16
    load_balancer_cidr: 10.23.1.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: 10.18.1.240
    username: admin
    password: ENC[AES256_GCM,data:hWflFIo/nucOFjHidC7Leks//TTtmcD2eOEz,iv:NwUDtbvG0CpbeoKqhdWuUpV39XDzKKWO7DAxoWR9+vs=,tag:MewRaozUw81VHkweO8Eg2A==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
    files:
        server: rickhouse.shortrib.run
        export: /opossum
acme:
    email: crdant@shortrib.io
cloudflare:
    api_token: GXvj-gJLYFNzBV97rBitL3_JERgSziM5Z4CbLeKm
tailscale:
    client_id: kj6YyWz1Hp11CNTRL
    client_secret: ENC[AES256_GCM,data:wL3pJnbeG1sETHE3MJduPe5VELKbNoLcAVRw5n2iNG43eXSNqzRM+bygHFXClFAY5nDI39EroZHYPJd+nvT8yw==,iv:i5QCQh8/OqUw7hHoXfA+psZRK0pNMHrMWumIgvY3v/M=,tag:hyY8o3rA8jkLo6nETey8Gg==,type:str]
sops:
    lastmodified: "2026-04-14T02:18:30Z"
    mac: ENC[AES256_GCM,data:EtQH9To1eJcHQY5K/Yi3C3j/nm0V0UhNEraPxXe9/Vw9+YAWe7PqBjmgz6LL/+rKZ76r7xmt6ETBOk2dNk7riNSLbPRs5wH6SwtvooYeTfaEX2php/dLwXy1HtnPgLcshqPzMgipt3wT1oGIK3cjek4cKjR6t7USC/Z0ptG/420=,iv:izDLDvQL0glNUrZGf3fGnrNhgsS1h4XWovoNDWlIKwE=,tag:29sJzCUyJLBpFptn55xICQ==,type:str]
    pgp:
        - created_at: "2026-04-14T02:18:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA6eG30ZRq1GWXXmx+M8dMq68mGfcWn5F5nqDTSZLKhhcw
            Fvv+wPOTS1Qi8uk3OuO6qjp9zBmjQt+wBrzwP35aGy3jnsOW5ttmLStE9XX0TQ89
            0l4BJI0ZkB9EUxuxt/35um1GOcaWijgYWPwWyHUfDICh+eism3yDxTQq1N//jTGY
            9284V5hQfGjDtTM9YXMPqOwVhIHcis3gzm+Lly+8wR2XE8TgXNTuBc/urokY/hXO
            =2slH
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
