cluster_name: opossum
domain: lab.shortrib.net
cluster_image_name: metal-amd64.iso
default_password: ENC[AES256_GCM,data:/8oAiVBtdzxmJosNlHi9Rwq5j5trtMMQUA==,iv:u9TES3gsIEMHsBXzQ2m/AyiLiG1sEFXj7MOLTNevWDg=,tag:ej3wTQzBQoQfI8Pv/gS3Lw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:01:0a
    kubernetes_cidr: 10.24.0.0/16
    load_balancer_cidr: 10.23.1.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: 10.18.1.240
    username: admin
    password: ENC[AES256_GCM,data:xBGucRWSio8cGzpE3fZDg6+/iJwKZbU0VsrR8c6t,iv:FSVbo1KmszG9NNkiKtdNzyI/TwFWWUGS7Da3Z2Opa7k=,tag:J0SvvC67+gUtIkiTSFb74A==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
    files:
        server: rickhouse.shortrib.run
        export: /opossum
acme:
    email: crdant@shortrib.io
cloudflare:
    api_token: GXvj-gJLYFNzBV97rBitL3_JERgSziM5Z4CbLeKm
tailscale:
    client_id: kj6YyWz1Hp11CNTRL
    client_secret: ENC[AES256_GCM,data:C35wResLBDxFQRuLfAaxL6p2Un+gS9yUuj6kXKpR6ISAd6156KKAilZjazQDjAKlu2Ap6QCxKKy0bTBIM5Xjfw==,iv:WdJRptBBEwAPMtUm90XRWZYh4+XGfy4dPCA5mUwh0x0=,tag:u+su0aHV2tOKB4STA0H7hQ==,type:str]
sops:
    lastmodified: "2026-01-14T15:19:35Z"
    mac: ENC[AES256_GCM,data:wBr5yQAC2jfTe4qD8rVMSH/96JalKTVHwhRDDcJraEyQBBLmDuCHLc21VaxQdBUybePJmW3Lb9KM1qh4S3BZTBwnM7Hqi3dhwPGw4ju0X2U1urLSjiNS2Us+ew5VGpPnDtGcToD3e3f8Rw/ngyZiZAQYP4d1N81iFKtbthENjdQ=,iv:uJdzjAki7nUFhSQvC5JKB8LKJju6UTlMqMPB2aERFl4=,tag:rzufTVSThup+gyj6R6BdRQ==,type:str]
    pgp:
        - created_at: "2026-01-14T15:19:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAaDEybwR35asp1N7joUeNiTBe4BWfvWUyKHUyC5ElkwYw
            TBcxeohJf2HxlznYXCfPCr3nJc3nzkogqXTDFsyBh/RA+elNGKZ4xnHDY/MoG3hn
            0lwBOTwkLEn5LQxYdJcYkpr4IhNhoI6YLAo45RO5e+7jpUmPQiMawyN/KHeUOnr1
            WtmxPaSyKbUYAGyJUljinCGgEc28bImGmeDyMo7Np4OglbPJ7EU+QpHGGhkMuQ==
            =TS7p
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
