cluster_name: skunk
domain: lab.shortrib.net
cluster_image_name: metal-amd64.iso
default_password: ENC[AES256_GCM,data:8R1AvljqYO5kcOm1QUqvdyUh7cpU8f4sJw==,iv:6ZIk1QOtVjUEKEfm346m3Dh/fHx1Cn9/JYKdJJ2tqEo=,tag:miVB75C7M5mf6F80Af3PVg==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:05:0a
    kubernetes_cidr: 10.24.5.0/16
    load_balancer_cidr: 10.23.5.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: 10.18.1.240
    username: admin
    password: ENC[AES256_GCM,data:7CI4kIaX29jfDkkEYNlYGhe7cx4oqsXRdZjqwLXh,iv:wvsoSKc25emiOuOVOpi/SPJji4w3mzRqleV0QJXw5zs=,tag:q9vCL1DBPtFCOHwFwg9Sqg==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
    files:
        server: rickhouse.shortrib.run
        export: /opossum
acme:
    email: crdant@shortrib.io
cloudflare:
    api_token: GXvj-gJLYFNzBV97rBitL3_JERgSziM5Z4CbLeKm
tailscale:
    client_id: kTNk152rem11CNTRL
    client_secret: ENC[AES256_GCM,data:YUusY9jpLfpwUmWuep2zEF9dvCWHUdP/6eidQkWS0nXqiQaJuFzdLpjtDeVbkhOet0fJPQ+KicmEbWUnFy7C0A==,iv:6A+Ebl1iWQ8DIJ+kJLahqSVoTCZvilNgW46ctXyI/Ho=,tag:iUDp683wiJwU4PYxzvaPvw==,type:str]
sops:
    lastmodified: "2026-02-13T14:23:24Z"
    mac: ENC[AES256_GCM,data:HoI9uwfubxrlV3ZkUViHN8a7U8hJCNA7HyqxqOPkRFxFlBf/3wk3txll36ZmZ3vI7sOYAdQoaCBPAZwUHQ7/KAaqFbdRyxO7xXaKvfgT4ZOgoqrgepW+fGhQLtytARV3F3PVRrVCWeif/wKrPHSIM0lnIdo/5W9XnmmwNjTRl/o=,iv:OPXYrzBJca0shGxQcY4L1GfCvdboZd2Qb9gBz54/k4o=,tag:lQC48vmqT7ap78z5emrEwg==,type:str]
    pgp:
        - created_at: "2026-02-13T14:23:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdALDYWjKxSv8ZzFAug3QnbbxAQrzCoNqbSzGUb4+u2uFEw
            UrTqRiHtv3iPU8nuujidHua+jP7nrEWtjidfxHvDFxoNxk/lsAxnNer88bUqpLVB
            0l4B2J71I8B1327ThHgDjt48ceuCD9N4DeJoEwrN69SrQPE+75+lHvNVKz2oel/t
            P9uoaL087kauZPByLK76Mq8bJ8Vyn6NN+3nUOrpNW01Mrkg+8+5N4/bsVBp49jHq
            =C4kV
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
